// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Stytch.net.Exceptions;
using Stytch.net.Models.Consumer;




namespace Stytch.net.Clients.Consumer
{
    public class M2M
    {
        private readonly ClientConfig _config;
        private readonly HttpClient _httpClient;
        public readonly M2MClients Clients;
        public M2M(HttpClient client, ClientConfig config)
        {
            _httpClient = client;
            _config = config;
            Clients = new M2MClients(_httpClient, _config);
        }


    }

}

