// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Stytch.net.Exceptions;
using Stytch.net.Models;




namespace Stytch.net.Clients.Consumer
{
    public class MagicLinks
    {
        private readonly ClientConfig _config;
        private readonly HttpClient _httpClient;
        public readonly MagicLinksEmail Email;
        public MagicLinks(HttpClient client, ClientConfig config)
        {
            _httpClient = client;
            _config = config;
            Email = new MagicLinksEmail(_httpClient, _config);
        }

        /// <summary>
        /// Authenticate a User given a Magic Link. This endpoint verifies that the Magic Link token is valid,
        /// hasn't expired or been previously used, and any optional security settings such as IP match or user
        /// agent match are satisfied.
        /// </summary>
        public async Task<MagicLinksAuthenticateResponse> Authenticate(
            MagicLinksAuthenticateRequest request
        )
        {
            var method = HttpMethod.Post;
            var uriBuilder = new UriBuilder(_httpClient.BaseAddress)
            {
                Path = $"/v1/magic_links/authenticate"
            };

            var httpReq = new HttpRequestMessage(method, uriBuilder.ToString());
            var jsonSettings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            };
            var jsonBody = JsonConvert.SerializeObject(request, jsonSettings);
            var content = new StringContent(jsonBody, Encoding.UTF8, "application/json");
            httpReq.Content = content;

            var response = await _httpClient.SendAsync(httpReq);
            var responseBody = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                return JsonConvert.DeserializeObject<MagicLinksAuthenticateResponse>(responseBody);
            }
            try
            {
                var apiException = JsonConvert.DeserializeObject<StytchApiException>(responseBody);
                throw apiException;
            }
            catch (JsonException)
            {
                throw new StytchNetworkException($"Unexpected error occurred: {responseBody}", response);
            }
        }
        /// <summary>
        /// Create an Embeddable Magic Link token for a User. Access to this endpoint is restricted. To enable it,
        /// please send us a note at support@stytch.com.
        /// 
        /// ### Next steps
        /// Send the returned `token` value to the end user in a link which directs to your application. When the
        /// end user follows your link, collect the token, and call
        /// [Authenticate Magic Link](https://stytch.com/docs/api/authenticate-magic-link) to complete
        /// authentication.
        /// 
        /// **Note:** Authenticating an Embeddable Magic Link token will **not** result in any of the Stytch User's
        /// factors (email address or phone number) being marked as verified, as Stytch cannot confirm where the
        /// user received the token.
        /// </summary>
        public async Task<MagicLinksCreateResponse> Create(
            MagicLinksCreateRequest request
        )
        {
            var method = HttpMethod.Post;
            var uriBuilder = new UriBuilder(_httpClient.BaseAddress)
            {
                Path = $"/v1/magic_links"
            };

            var httpReq = new HttpRequestMessage(method, uriBuilder.ToString());
            var jsonSettings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            };
            var jsonBody = JsonConvert.SerializeObject(request, jsonSettings);
            var content = new StringContent(jsonBody, Encoding.UTF8, "application/json");
            httpReq.Content = content;

            var response = await _httpClient.SendAsync(httpReq);
            var responseBody = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                return JsonConvert.DeserializeObject<MagicLinksCreateResponse>(responseBody);
            }
            try
            {
                var apiException = JsonConvert.DeserializeObject<StytchApiException>(responseBody);
                throw apiException;
            }
            catch (JsonException)
            {
                throw new StytchNetworkException($"Unexpected error occurred: {responseBody}", response);
            }
        }

    }

}
