// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

using Newtonsoft.Json;
using Stytch.net.Exceptions;
using Stytch.net.Models.Consumer;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;




namespace Stytch.net.Clients.Consumer
{
  public class PasswordsExistingPassword
  {
    private readonly ClientConfig _config;
    private readonly HttpClient _httpClient;
    public PasswordsExistingPassword(HttpClient client, ClientConfig config)
    {
      _httpClient = client;
      _config = config;
    }

    /// <summary>
    /// Reset the User’s password using their existing password.
    /// 
    /// Note that a successful password reset via an existing password will revoke all active sessions for the
    /// `user_id`.
    /// </summary>
    public async Task<PasswordsExistingPasswordResetResponse> Reset(
        PasswordsExistingPasswordResetRequest request
    )
    {
        var method = HttpMethod.Post;
        var uriBuilder = new UriBuilder(_httpClient.BaseAddress){
          Path = $"/v1/passwords/existing_password/reset"
        };

        var httpReq = new HttpRequestMessage(method, uriBuilder.ToString());
        var jsonSettings = new JsonSerializerSettings
        {
            NullValueHandling = NullValueHandling.Ignore
        };
        var jsonBody = JsonConvert.SerializeObject(request, jsonSettings);
        var content = new StringContent(jsonBody, Encoding.UTF8, "application/json");
        httpReq.Content = content;

        var response = await _httpClient.SendAsync(httpReq);
        var responseBody = await response.Content.ReadAsStringAsync();

        if (response.IsSuccessStatusCode)
        {
            return JsonConvert.DeserializeObject<PasswordsExistingPasswordResetResponse>(responseBody);
        }
        try
        {
            var apiException = JsonConvert.DeserializeObject<StytchApiException>(responseBody);
            throw apiException;
        }
        catch (JsonException)
        {
            throw new StytchNetworkException($"Unexpected error occurred: {responseBody}", response);
        }
    }

  }

}

