// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

using Newtonsoft.Json;
using Stytch.net.Models.Consumer;
using System.Text;




namespace Stytch.net.Clients.Consumer
{
    public class PasswordsExistingPassword
    {
        private readonly HttpClient _httpClient;
        public PasswordsExistingPassword(HttpClient client)
        {
            _httpClient = client;
        }

        /// <summary>
        /// Reset the User’s password using their existing password.
        /// 
        /// Note that a successful password reset via an existing password will revoke all active sessions for the
        /// `user_id`.
        /// </summary>
        public async Task<PasswordsExistingPasswordResetResponse> Reset(
            PasswordsExistingPasswordResetRequest request)
        {
            var method = HttpMethod.Post;
            var uriBuilder = new UriBuilder($"/v1/passwords/existing_password/reset");

            var httpReq = new HttpRequestMessage(method, uriBuilder.ToString());
            var jsonBody = JsonConvert.SerializeObject(request);
            var content = new StringContent(jsonBody, Encoding.UTF8, "application/json");
            httpReq.Content = content;

            var response = await _httpClient.SendAsync(httpReq);
            var responseBody = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                return JsonConvert.DeserializeObject<PasswordsExistingPasswordResetResponse>(responseBody)!;
            }
            else
            {
                // Optionally, throw an exception or return null or an error object
                throw new HttpRequestException(
                    $"Request failed with status code {response.StatusCode}: {responseBody}");
            }
        }

    }

}

