// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Stytch.net.Models.Consumer
{
public class Attributes {
      // The IP address of the user.
      [JsonProperty("ip_address")]
      public string? IpAddress { get; set; }
      // The user agent of the User.
      [JsonProperty("user_agent")]
      public string? UserAgent { get; set; }
    }

}