// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Runtime.Serialization;
using System.Collections.Generic;


namespace Stytch.net.Models.Consumer
{
    /// <summary>
    /// Request type for <see cref="Stytch.net.Clients.Consumer.M2M.Clients.Secrets.RotateCancel"/>..
    /// </summary>
    public class M2MClientsSecretsRotateCancelRequest
    {
        /// <summary>
        /// The ID of the client.
        /// </summary>
        [JsonProperty("client_id")]
        public string ClientId { get; set; }
        public M2MClientsSecretsRotateCancelRequest(string clientId)
        {
            this.ClientId = clientId;
        }
    }
    /// <summary>
    /// Response type for <see cref="Stytch.net.Clients.Consumer.M2M.Clients.Secrets.RotateCancel"/>..
    /// </summary>
    public class M2MClientsSecretsRotateCancelResponse
    {
        /// <summary>
        /// Globally unique UUID that is returned with every API call. This value is important to log for debugging
        /// purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
        /// </summary>
        [JsonProperty("request_id")]
        public string RequestId { get; set; }
        /// <summary>
        /// The M2M Client affected by this operation.
        /// </summary>
        [JsonProperty("m2m_client")]
        public M2MClient M2MClient { get; set; }
        /// <summary>
        /// The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
        /// 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
        /// </summary>
        [JsonProperty("status_code")]
        public int StatusCode { get; set; }
    }
    /// <summary>
    /// Request type for <see cref="Stytch.net.Clients.Consumer.M2M.Clients.Secrets.Rotate"/>..
    /// </summary>
    public class M2MClientsSecretsRotateRequest
    {
        /// <summary>
        /// The ID of the client.
        /// </summary>
        [JsonProperty("client_id")]
        public string ClientId { get; set; }
        public M2MClientsSecretsRotateRequest(string clientId)
        {
            this.ClientId = clientId;
        }
    }
    /// <summary>
    /// Response type for <see cref="Stytch.net.Clients.Consumer.M2M.Clients.Secrets.Rotate"/>..
    /// </summary>
    public class M2MClientsSecretsRotateResponse
    {
        /// <summary>
        /// Globally unique UUID that is returned with every API call. This value is important to log for debugging
        /// purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
        /// </summary>
        [JsonProperty("request_id")]
        public string RequestId { get; set; }
        /// <summary>
        /// The M2M Client affected by this operation.
        /// </summary>
        [JsonProperty("m2m_client")]
        public M2MClient M2MClient { get; set; }
        /// <summary>
        /// The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
        /// 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
        /// </summary>
        [JsonProperty("status_code")]
        public int StatusCode { get; set; }
    }
    /// <summary>
    /// Request type for <see cref="Stytch.net.Clients.Consumer.M2M.Clients.Secrets.RotateStart"/>..
    /// </summary>
    public class M2MClientsSecretsRotateStartRequest
    {
        /// <summary>
        /// The ID of the client.
        /// </summary>
        [JsonProperty("client_id")]
        public string ClientId { get; set; }
        public M2MClientsSecretsRotateStartRequest(string clientId)
        {
            this.ClientId = clientId;
        }
    }
    /// <summary>
    /// Response type for <see cref="Stytch.net.Clients.Consumer.M2M.Clients.Secrets.RotateStart"/>..
    /// </summary>
    public class M2MClientsSecretsRotateStartResponse
    {
        /// <summary>
        /// Globally unique UUID that is returned with every API call. This value is important to log for debugging
        /// purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
        /// </summary>
        [JsonProperty("request_id")]
        public string RequestId { get; set; }
        /// <summary>
        /// The M2M Client affected by this operation.
        /// </summary>
        [JsonProperty("m2m_client")]
        public M2MClientWithNextClientSecret M2MClient { get; set; }
        /// <summary>
        /// The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
        /// 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
        /// </summary>
        [JsonProperty("status_code")]
        public int StatusCode { get; set; }
    }

}