// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Stytch.net.Models.Consumer
{
// Request type for `otps.email.loginOrCreate`.
    public class OTPsEmailLoginOrCreateRequest {
      /**
    * The email address of the user to send the one-time passcode to. You may use sandbox@stytch.com to test
    * this endpoint, see [Testing](https://stytch.com/docs/home#resources_testing) for more detail.
    */
      [JsonProperty("email")]
      public required string Email { get; set; }
      /**
    * Set the expiration for the one-time passcode, in minutes. The minimum expiration is 1 minute and the
    * maximum is 10 minutes. The default expiration is 2 minutes.
    */
      [JsonProperty("expiration_minutes")]
      public int? ExpirationMinutes { get; set; }
      // Provided attributes help with fraud detection.
      [JsonProperty("attributes")]
      public Attributes? Attributes { get; set; }
      /**
    * Flag for whether or not to save a user as pending vs active in Stytch. Defaults to false.
    *         If true, users will be saved with status pending in Stytch's backend until authenticated.
    *         If false, users will be created as active. An example usage of
    *         a true flag would be to require users to verify their phone by entering the OTP code before
    * creating
    *         an account for them.
    */
      [JsonProperty("create_user_as_pending")]
      public bool? CreateUserAsPending { get; set; }
      /**
    * Used to determine which language to use when sending the user this delivery method. Parameter is a
    * [IETF BCP 47 language tag](https://www.w3.org/International/articles/language-tags/), e.g. `"en"`.
    * 
    * Currently supported languages are English (`"en"`), Spanish (`"es"`), and Brazilian Portuguese
    * (`"pt-br"`); if no value is provided, the copy defaults to English.
    * 
    * Request support for additional languages
    * [here](https://docs.google.com/forms/d/e/1FAIpQLScZSpAu_m2AmLXRT3F3kap-s_mcV6UTBitYn6CdyWP0-o7YjQ/viewform?usp=sf_link")!
    * 
    */
      [JsonProperty("locale")]
      public OTPsEmailLoginOrCreateRequestLocale? Locale { get; set; }
      /**
    * Use a custom template for login emails. By default, it will use your default email template. The
    * template must be a template using our built-in customizations or a custom HTML email for Magic links -
    * Login.
    */
      [JsonProperty("login_template_id")]
      public string? LoginTemplateId { get; set; }
      /**
    * Use a custom template for sign-up emails. By default, it will use your default email template. The
    * template must be a template using our built-in customizations or a custom HTML email for Magic links -
    * Sign-up.
    */
      [JsonProperty("signup_template_id")]
      public string? SignupTemplateId { get; set; }
    }
// Response type for `otps.email.loginOrCreate`.
    public class OTPsEmailLoginOrCreateResponse {
      /**
    * Globally unique UUID that is returned with every API call. This value is important to log for debugging
    * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
    */
      [JsonProperty("request_id")]
      public required string RequestId { get; set; }
      // The unique ID of the affected User.
      [JsonProperty("user_id")]
      public required string UserId { get; set; }
      // The unique ID of a specific email address.
      [JsonProperty("email_id")]
      public required string EmailId { get; set; }
      // In `login_or_create` endpoints, this field indicates whether or not a User was just created.
      [JsonProperty("user_created")]
      public required bool UserCreated { get; set; }
      /**
    * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
    * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
    */
      [JsonProperty("status_code")]
      public required int StatusCode { get; set; }
    }
// Request type for `otps.email.send`.
    public class OTPsEmailSendRequest {
      /**
    * The email address of the user to send the one-time passcode to. You may use sandbox@stytch.com to test
    * this endpoint, see [Testing](https://stytch.com/docs/home#resources_testing) for more detail.
    */
      [JsonProperty("email")]
      public required string Email { get; set; }
      /**
    * Set the expiration for the one-time passcode, in minutes. The minimum expiration is 1 minute and the
    * maximum is 10 minutes. The default expiration is 2 minutes.
    */
      [JsonProperty("expiration_minutes")]
      public int? ExpirationMinutes { get; set; }
      // Provided attributes help with fraud detection.
      [JsonProperty("attributes")]
      public Attributes? Attributes { get; set; }
      /**
    * Used to determine which language to use when sending the user this delivery method. Parameter is a
    * [IETF BCP 47 language tag](https://www.w3.org/International/articles/language-tags/), e.g. `"en"`.
    * 
    * Currently supported languages are English (`"en"`), Spanish (`"es"`), and Brazilian Portuguese
    * (`"pt-br"`); if no value is provided, the copy defaults to English.
    * 
    * Request support for additional languages
    * [here](https://docs.google.com/forms/d/e/1FAIpQLScZSpAu_m2AmLXRT3F3kap-s_mcV6UTBitYn6CdyWP0-o7YjQ/viewform?usp=sf_link")!
    * 
    */
      [JsonProperty("locale")]
      public OTPsEmailSendRequestLocale? Locale { get; set; }
      // The unique ID of a specific User.
      [JsonProperty("user_id")]
      public string? UserId { get; set; }
      // The `session_token` associated with a User's existing Session.
      [JsonProperty("session_token")]
      public string? SessionToken { get; set; }
      // The `session_jwt` associated with a User's existing Session.
      [JsonProperty("session_jwt")]
      public string? SessionJwt { get; set; }
      /**
    * Use a custom template for login emails. By default, it will use your default email template. The
    * template must be a template using our built-in customizations or a custom HTML email for Magic links -
    * Login.
    */
      [JsonProperty("login_template_id")]
      public string? LoginTemplateId { get; set; }
      /**
    * Use a custom template for sign-up emails. By default, it will use your default email template. The
    * template must be a template using our built-in customizations or a custom HTML email for Magic links -
    * Sign-up.
    */
      [JsonProperty("signup_template_id")]
      public string? SignupTemplateId { get; set; }
    }
// Response type for `otps.email.send`.
    public class OTPsEmailSendResponse {
      /**
    * Globally unique UUID that is returned with every API call. This value is important to log for debugging
    * purposes; we may ask for this value to help identify a specific API call when helping you debug an issue.
    */
      [JsonProperty("request_id")]
      public required string RequestId { get; set; }
      // The unique ID of the affected User.
      [JsonProperty("user_id")]
      public required string UserId { get; set; }
      // The unique ID of a specific email address.
      [JsonProperty("email_id")]
      public required string EmailId { get; set; }
      /**
    * The HTTP status code of the response. Stytch follows standard HTTP response status code patterns, e.g.
    * 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX are server errors.
    */
      [JsonProperty("status_code")]
      public required int StatusCode { get; set; }
    }

public enum OTPsEmailLoginOrCreateRequestLocale
    {
      [EnumMember(Value = "en")]
      EN,
      [EnumMember(Value = "es")]
      ES,
      [EnumMember(Value = "pt-br")]
      PTBR,
    }
public enum OTPsEmailSendRequestLocale
    {
      [EnumMember(Value = "en")]
      EN,
      [EnumMember(Value = "es")]
      ES,
      [EnumMember(Value = "pt-br")]
      PTBR,
    }
}