// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Stytch.net.Models
{
    public class RBACPolicy
    {
        [JsonProperty("roles")]
        public List<RBACPolicyRole> Roles { get; set; }
        [JsonProperty("resources")]
        public List<RBACPolicyResource> Resources { get; set; }
        [JsonProperty("scopes")]
        public List<RBACPolicyScope> Scopes { get; set; }
    }
    public class RBACPolicyResource
    {
        [JsonProperty("resource_id")]
        public string ResourceId { get; set; }
        [JsonProperty("description")]
        public string Description { get; set; }
        [JsonProperty("actions")]
        public List<string> Actions { get; set; }
    }
    public class RBACPolicyRole
    {
        [JsonProperty("role_id")]
        public string RoleId { get; set; }
        [JsonProperty("description")]
        public string Description { get; set; }
        [JsonProperty("permissions")]
        public List<RBACPolicyRolePermission> Permissions { get; set; }
    }
    public class RBACPolicyRolePermission
    {
        [JsonProperty("resource_id")]
        public string ResourceId { get; set; }
        [JsonProperty("actions")]
        public List<string> Actions { get; set; }
    }
    public class RBACPolicyScope
    {
        [JsonProperty("scope")]
        public string Scope { get; set; }
        [JsonProperty("description")]
        public string Description { get; set; }
        [JsonProperty("permissions")]
        public List<RBACPolicyScopePermission> Permissions { get; set; }
    }
    public class RBACPolicyScopePermission
    {
        [JsonProperty("resource_id")]
        public string ResourceId { get; set; }
        [JsonProperty("actions")]
        public List<string> Actions { get; set; }
    }
    public class RBACPolicyRequest
    {
        public RBACPolicyRequest()
        {
        }
    }
    public class RBACPolicyResponse
    {
        [JsonProperty("request_id")]
        public string RequestId { get; set; }
        [JsonProperty("status_code")]
        public int StatusCode { get; set; }
        [JsonProperty("policy")]
        public RBACPolicy Policy { get; set; }
    }

}
