// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Stytch.net.Models
{
    public class DiscoveredOrganization
    {
        /// <summary>
        /// Indicates whether the Member has all of the factors needed to fully authenticate to this Organization.
        /// If false, the Member may need to complete an MFA step or complete a different primary authentication
        /// flow. See the `primary_required` and `mfa_required` fields for more details on each.
        /// </summary>
        [JsonProperty("member_authenticated")]
        public bool MemberAuthenticated { get; set; }
        /// <summary>
        /// The [Organization object](https://stytch.com/docs/b2b/api/organization-object).
        /// </summary>
        [JsonProperty("organization")]
        public Organization Organization { get; set; }
        /// <summary>
        /// Information about the membership.
        /// </summary>
        [JsonProperty("membership")]
        public Membership Membership { get; set; }
        /// <summary>
        /// Information about the primary authentication requirements of the Organization.
        /// </summary>
        [JsonProperty("primary_required")]
        public PrimaryRequired PrimaryRequired { get; set; }
        /// <summary>
        /// Information about the MFA requirements of the Organization and the Member's options for fulfilling MFA.
        /// </summary>
        [JsonProperty("mfa_required")]
        public MfaRequired MfaRequired { get; set; }
    }
    public class Membership
    {
        /// <summary>
        /// Either `active_member`, `pending_member`, `invited_member`, `eligible_to_join_by_email_domain`, or
        /// `eligible_to_join_by_oauth_tenant`
        /// </summary>
        [JsonProperty("type")]
        public string Type { get; set; }
        /// <summary>
        /// An object containing additional metadata about the membership, if available.
        /// </summary>
        [JsonProperty("details")]
        public object Details { get; set; }
        /// <summary>
        /// The [Member object](https://stytch.com/docs/b2b/api/member-object) if one already exists, or null if one
        /// does not.
        /// </summary>
        [JsonProperty("member")]
        public Member Member { get; set; }
    }

}
