// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace Stytch.net.Models.Consumer
{
public class MemberOptions {
      // The Member's MFA phone number.
      [JsonProperty("mfa_phone_number")]
      public required string MfaPhoneNumber { get; set; }
      // The Member's MFA TOTP registration ID.
      [JsonProperty("totp_registration_id")]
      public required string TOTPRegistrationId { get; set; }
    }
public class MfaRequired {
      // Information about the Member's options for completing MFA.
      [JsonProperty("member_options")]
      public MemberOptions? MemberOptions { get; set; }
      /**
    * If null, indicates that no secondary authentication has been initiated. If equal to "sms_otp", indicates
    * that the Member has a phone number, and a one time passcode has been sent to the Member's phone number.
    * No secondary authentication will be initiated during calls to the discovery authenticate or list
    * organizations endpoints, even if the Member has a phone number.
    */
      [JsonProperty("secondary_auth_initiated")]
      public string? SecondaryAuthInitiated { get; set; }
    }

}