// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Stytch.net.Models.Consumer
{
    public class B2BSSOExternalCreateConnectionRequestOptions
    {
        /// <summary>
        /// Optional authorization object.
        /// Pass in an active Stytch Member session token or session JWT and the request
        /// will be run using that member's permissions.
        /// </summary>
        [JsonProperty("authorization")]
        public Authorization Authorization { get; set; }
    }
    public class B2BSSOExternalUpdateConnectionRequestOptions
    {
        /// <summary>
        /// Optional authorization object.
        /// Pass in an active Stytch Member session token or session JWT and the request
        /// will be run using that member's permissions.
        /// </summary>
        [JsonProperty("authorization")]
        public Authorization Authorization { get; set; }
    }
    public class B2BSSOExternalCreateConnectionRequest
    {
        [JsonProperty("organization_id")]
        public string OrganizationId { get; set; }
        [JsonProperty("external_organization_id")]
        public string ExternalOrganizationId { get; set; }
        [JsonProperty("external_connection_id")]
        public string ExternalConnectionId { get; set; }
        [JsonProperty("display_name")]
        public string DisplayName { get; set; }
        [JsonProperty("connection_implicit_role_assignments")]
        public List<SAMLConnectionImplicitRoleAssignment> ConnectionImplicitRoleAssignments { get; set; }
        [JsonProperty("group_implicit_role_assignments")]
        public List<SAMLGroupImplicitRoleAssignment> GroupImplicitRoleAssignments { get; set; }
        public B2BSSOExternalCreateConnectionRequest(string organizationId, string externalOrganizationId, string externalConnectionId)
        {
            this.OrganizationId = organizationId;
            this.ExternalOrganizationId = externalOrganizationId;
            this.ExternalConnectionId = externalConnectionId;
        }
    }
    public class B2BSSOExternalCreateConnectionResponse
    {
        [JsonProperty("request_id")]
        public string RequestId { get; set; }
        [JsonProperty("status_code")]
        public int StatusCode { get; set; }
        [JsonProperty("connection")]
        public Connection Connection { get; set; }
    }
    public class B2BSSOExternalUpdateConnectionRequest
    {
        [JsonProperty("organization_id")]
        public string OrganizationId { get; set; }
        [JsonProperty("connection_id")]
        public string ConnectionId { get; set; }
        [JsonProperty("display_name")]
        public string DisplayName { get; set; }
        [JsonProperty("external_connection_implicit_role_assignments")]
        public List<ConnectionImplicitRoleAssignment> ExternalConnectionImplicitRoleAssignments { get; set; }
        [JsonProperty("external_group_implicit_role_assignments")]
        public List<GroupImplicitRoleAssignment> ExternalGroupImplicitRoleAssignments { get; set; }
        public B2BSSOExternalUpdateConnectionRequest(string organizationId, string connectionId)
        {
            this.OrganizationId = organizationId;
            this.ConnectionId = connectionId;
        }
    }
    public class B2BSSOExternalUpdateConnectionResponse
    {
        [JsonProperty("request_id")]
        public string RequestId { get; set; }
        [JsonProperty("status_code")]
        public int StatusCode { get; set; }
        [JsonProperty("connection")]
        public Connection Connection { get; set; }
    }

}
