// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Stytch.net.Exceptions;
using Stytch.net.Models;




namespace Stytch.net.Clients.B2B
{
    public class OTPs
    {
        private readonly ClientConfig _config;
        private readonly HttpClient _httpClient;
        public readonly OTPsSms Sms;
        public readonly OTPsEmail Email;
        public OTPs(HttpClient client, ClientConfig config)
        {
            _httpClient = client;
            _config = config;
            Sms = new OTPsSms(_httpClient, _config);
            Email = new OTPsEmail(_httpClient, _config);
        }


    }

}
