// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Stytch.net.Exceptions;
using Stytch.net.Models.Consumer;




namespace Stytch.net.Clients.B2B
{
    public class PasswordsDiscoveryEmail
    {
        private readonly ClientConfig _config;
        private readonly HttpClient _httpClient;
        public PasswordsDiscoveryEmail(HttpClient client, ClientConfig config)
        {
            _httpClient = client;
            _config = config;
        }

        /// <summary>
        /// Initiates a password reset for the email address provided, when cross-org passwords are enabled. This
        /// will trigger an email to be sent to the address, containing a magic link that will allow them to set a
        /// new password and authenticate.
        /// 
        /// This endpoint adapts to your Project's password strength configuration.
        /// If you're using [zxcvbn](https://stytch.com/docs/guides/passwords/strength-policy), the default, your
        /// passwords are considered valid
        /// if the strength score is >= 3. If you're using
        /// [LUDS](https://stytch.com/docs/guides/passwords/strength-policy), your passwords are
        /// considered valid if they meet the requirements that you've set with Stytch.
        /// You may update your password strength configuration in the
        /// [stytch dashboard](https://stytch.com/dashboard/password-strength-config).
        /// </summary>
        public async Task<B2BPasswordsDiscoveryEmailResetStartResponse> ResetStart(
            B2BPasswordsDiscoveryEmailResetStartRequest request
        )
        {
            var method = HttpMethod.Post;
            var uriBuilder = new UriBuilder(_httpClient.BaseAddress)
            {
                Path = $"/v1/b2b/passwords/discovery/email/reset/start"
            };

            var httpReq = new HttpRequestMessage(method, uriBuilder.ToString());
            var jsonSettings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            };
            var jsonBody = JsonConvert.SerializeObject(request, jsonSettings);
            var content = new StringContent(jsonBody, Encoding.UTF8, "application/json");
            httpReq.Content = content;

            var response = await _httpClient.SendAsync(httpReq);
            var responseBody = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                return JsonConvert.DeserializeObject<B2BPasswordsDiscoveryEmailResetStartResponse>(responseBody);
            }
            try
            {
                var apiException = JsonConvert.DeserializeObject<StytchApiException>(responseBody);
                throw apiException;
            }
            catch (JsonException)
            {
                throw new StytchNetworkException($"Unexpected error occurred: {responseBody}", response);
            }
        }
        /// <summary>
        /// Reset the password associated with an email and start an intermediate session. This endpoint checks that
        /// the password reset token is valid, hasn’t expired, or already been used.
        /// 
        /// The provided password needs to meet the project's password strength requirements, which can be checked
        /// in advance with the password strength endpoint. If the token and password are accepted, the password is
        /// securely stored for future authentication and the user is authenticated.
        /// 
        /// Resetting a password will start an intermediate session and return a list of discovered organizations
        /// the session can be exchanged into.
        /// </summary>
        public async Task<B2BPasswordsDiscoveryEmailResetResponse> Reset(
            B2BPasswordsDiscoveryEmailResetRequest request
        )
        {
            var method = HttpMethod.Post;
            var uriBuilder = new UriBuilder(_httpClient.BaseAddress)
            {
                Path = $"/v1/b2b/passwords/discovery/email/reset"
            };

            var httpReq = new HttpRequestMessage(method, uriBuilder.ToString());
            var jsonSettings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore
            };
            var jsonBody = JsonConvert.SerializeObject(request, jsonSettings);
            var content = new StringContent(jsonBody, Encoding.UTF8, "application/json");
            httpReq.Content = content;

            var response = await _httpClient.SendAsync(httpReq);
            var responseBody = await response.Content.ReadAsStringAsync();

            if (response.IsSuccessStatusCode)
            {
                return JsonConvert.DeserializeObject<B2BPasswordsDiscoveryEmailResetResponse>(responseBody);
            }
            try
            {
                var apiException = JsonConvert.DeserializeObject<StytchApiException>(responseBody);
                throw apiException;
            }
            catch (JsonException)
            {
                throw new StytchNetworkException($"Unexpected error occurred: {responseBody}", response);
            }
        }

    }

}

