name: Publish NuGet package

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish stytch package to NuGet
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Get version
        id: version
        run: |
          VERSION=$(sed -n 's:.*<Version>\(.*\)</Version>.*:\1:p' Stytch.net/Stytch.net.csproj)
          echo "release_tag=$VERSION" >> $GITHUB_OUTPUT

      - name: Check for Stytch.net.csproj diff
        id: diff
        env:
          BASE_SHA: ${{ github.event.before }}
          HEAD_SHA: ${{ github.sha }}
        run: |
          git fetch --depth=1 origin "$BASE_SHA"
          if git diff --quiet "$BASE_SHA" "$HEAD_SHA" -- Stytch.net/Stytch.net.csproj; then
            echo "diff=0" >> $GITHUB_OUTPUT
          else
            echo "diff=1" >> $GITHUB_OUTPUT
          fi

      - name: Publish to NuGet
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: |
          dotnet pack -o ./build
          dotnet nuget push ./build/*.nupkg --source "nuget.org" --skip-duplicate --api-key $NUGET_KEY

      - name: Create release
        if: steps.diff.outputs.diff != 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ steps.version.outputs.release_tag }}" --generate-notes
